### ISSUE TITLE
Erro no plugin

### ISSUE THREAD

**Issue by salvadormarcos2000** [wpbrasil/wpbr-geouser#5]
Boa tarde amigos.

Infelizmente estou fazendo teste nesse plugin e infelizmente estou tendo problemas, pois não esta aparecendo nenhuma localização dos usuarios cadastrados no site de teste, apenas o meu cadastro aparece.

Segue link do site para melhor analise - 

http://tccetecmaua.esy.es/mapa/admin

infelizmente não sei oque pode ser;

Desde ja obrigado pela ajuda;

@salvadormacos

**Comment by vmassuchetto** [comment]
@salvadormarcos2000 , tente usar o plugin a partir do tema: https://github.com/wpbrasil/wpbr-mapa

**Comment by salvadormarcos2000** [comment]
Bom dia.

Estou utilizando exatamente os temas informados,o plugin esta OK, apenas e atualizado uma vez ao dia.

Pode fechar o tópico, obrigado pela ajuda.

ats

**Comment by vmassuchetto** [comment]
Não entendi @salvadormarcos2000 , você conseguiu fazer tudo funcionar?

**Comment by salvadormarcos2000** [comment]
Consegui, só que é preciso aguardar 24hrs para atualizar, segue o link do site.
http://tccetecmaua.esy.es/

estou utilizando o mesmo em teste com multisite;

ats
